<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Destination;

class LargeDestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Add new destinations (don't truncate because of foreign key constraints)

        $destinations = [
            // Góry i Tatry
            [
                'name' => 'Zakopane',
                'description' => 'Stolica polskich Tatr - góry, kuligi i oscypek',
                'long_description' => 'Zakopane to prawdziwa perła polskich gór, położona u stóp majestykatycznych Tatr. Miejsce gdzie tradycja góralska spotyka się z nowoczesnym turystyką.',
                'image' => '/images/destinations/zakopane-main.jpg',
                'price' => 199.00,
                'original_price' => 249.00,
                'type' => 'Weekend',
                'duration' => '3 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Narty/snowboard', 'Wędrówki górskie', 'Kuligi']),
                'highlights' => json_encode(['Kasprowy Wierch', 'Morskie Oko', 'Krupówki']),
                'category' => 'górskie',
                'difficulty' => 'średni',
                'season' => 'cały rok',
                'gallery' => json_encode([]),
                'included' => json_encode(['Noclegi', 'Śniadania', 'Przewodnik']),
                'not_included' => json_encode(['Obiady', 'Kolacje']),
                'city' => 'Zakopane',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Karpacz',
                'description' => 'Największy kurort w Sudetach u stóp Śnieżki',
                'long_description' => 'Karpacz to największy kurort w polskich Sudetach, położony malowniczo u stóp najwyższego szczytu Śnieżki.',
                'image' => '/images/destinations/karpacz-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'Weekend',
                'duration' => '3 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Wędrówki górskie', 'Narciarstwo', 'Nordic walking']),
                'highlights' => json_encode(['Śnieżka', 'Wang', 'Kolejka linowa']),
                'category' => 'górskie',
                'region' => 'Dolnośląskie',
                'active' => true,
            ],
            [
                'name' => 'Bukowina Tatrzańska',
                'description' => 'Spokojne miejsce u podnóża Tatr',
                'long_description' => 'Bukowina Tatrzańska to urokliwe miejsce oferujące spokojny wypoczynek z widokiem na Tatry.',
                'image' => '/images/destinations/bukowina-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Relaks',
                'duration' => '2 dni',
                'rating' => 4.4,
                'activities' => json_encode(['Termy', 'Spacery', 'Fotografia']),
                'highlights' => json_encode(['Termy Bukovina', 'Rusinowa Polana', 'Tatry']),
                'category' => 'górskie',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Szczyrk',
                'description' => 'Perła Beskidu Śląskiego',
                'long_description' => 'Szczyrk to jeden z najbardziej znanych kurortów górskich w Polsce, położony w Beskidzie Śląskim.',
                'image' => '/images/destinations/szczyrk-main.jpg',
                'price' => 169.00,
                'original_price' => 209.00,
                'type' => 'Aktywny',
                'duration' => '3 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Narciarstwo', 'Hiking', 'Biking']),
                'highlights' => json_encode(['Skrzyczne', 'Dojazd kolejką', 'Klimczok']),
                'category' => 'górskie',
                'region' => 'Śląskie',
                'active' => true,
            ],
            [
                'name' => 'Wisła',
                'description' => 'Perła Beskidu Śląskiego - miasto Adama Małysza',
                'long_description' => 'Wisła to malowniczy kurort górski w Beskidzie Śląskim, słynący z tradycji narciarskich.',
                'image' => '/images/destinations/wisla-main.jpg',
                'price' => 189.00,
                'original_price' => 229.00,
                'type' => 'Sport',
                'duration' => '3 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Skoki narciarskie', 'Narciarstwo', 'Museum Sportu']),
                'highlights' => json_encode(['Malinka', 'Skocznia', 'Barania Góra']),
                'category' => 'górskie',
                'region' => 'Śląskie',
                'active' => true,
            ],

            // Miasta historyczne
            [
                'name' => 'Kraków',
                'description' => 'Królewskie miasto pełne magii i historii',
                'long_description' => 'Kraków to dawna stolica Polski, miasto królów i artystów, wpisane na Listę Światowego Dziedzictwa UNESCO.',
                'image' => '/images/destinations/krakow-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'Weekend',
                'duration' => '3 dni',
                'rating' => 4.9,
                'activities' => json_encode(['Zwiedzanie', 'Kultura', 'Gastronomia']),
                'highlights' => json_encode(['Zamek Wawel', 'Sukiennice', 'Kazimierz']),
                'category' => 'kulturalne',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Gdańsk',
                'description' => 'Perła Bałtyku - historia, kultura i morze',
                'long_description' => 'Gdańsk to miasto o tysiącletniej historii, które zachwyca architekturą, kulturą i nadmorskim klimatem.',
                'image' => '/images/destinations/gdansk-main.jpg',
                'price' => 249.00,
                'original_price' => 299.00,
                'type' => 'City Break',
                'duration' => '4 dni',
                'rating' => 4.9,
                'activities' => json_encode(['Plaże', 'Muzea', 'Żuraw portowy']),
                'highlights' => json_encode(['Stare Miasto', 'Westerplatte', 'Sopot']),
                'category' => 'nadmorskie',
                'region' => 'Pomorskie',
                'active' => true,
            ],
            [
                'name' => 'Wrocław',
                'description' => 'Wenecja Północy z setkami mostów',
                'long_description' => 'Wrocław to miasto stu mostów i krasnali, stolica Dolnego Śląska pełna uroku i historii.',
                'image' => '/images/destinations/wroclaw-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'Weekend',
                'duration' => '3 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Krasnale', 'Rynek', 'Ostrów Tumski']),
                'highlights' => json_encode(['Stare Miasto', 'Rynek', 'Krasnale']),
                'category' => 'kulturalne',
                'region' => 'Dolnośląskie',
                'active' => true,
            ],
            [
                'name' => 'Poznań',
                'description' => 'Kolebka polskości z zabytkami',
                'long_description' => 'Poznań to kolebka polskości, miasto o bogatej historii i tradycjach, stolica Wielkopolski.',
                'image' => '/images/destinations/poznan-main.jpg',
                'price' => 169.00,
                'original_price' => 209.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Stary Rynek', 'Ratusz', 'Koziolki']),
                'highlights' => json_encode(['Stary Rynek', 'Ostrów Tumski', 'Cytadela']),
                'category' => 'kulturalne',
                'region' => 'Wielkopolskie',
                'active' => true,
            ],
            [
                'name' => 'Warszawa',
                'description' => 'Stolica Polski - nowoczesność i tradycja',
                'long_description' => 'Warszawa to dynamiczna stolica Polski łącząca nowoczesność z bogatą historią.',
                'image' => '/images/destinations/warszawa-main.jpg',
                'price' => 199.00,
                'original_price' => 249.00,
                'type' => 'Business',
                'duration' => '3 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Muzea', 'Teatry', 'Skyline']),
                'highlights' => json_encode(['Stare Miasto', 'Pałac Kultury', 'Łazienki']),
                'category' => 'kulturalne',
                'region' => 'Mazowieckie',
                'active' => true,
            ],
            [
                'name' => 'Lublin',
                'description' => 'Brama Wschodu z renesansowym urokiem',
                'long_description' => 'Lublin to miasto o wyjątkowej atmosferze, nazywane Bramą Wschodu, z piękną starówką.',
                'image' => '/images/destinations/lublin-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Stare Miasto', 'Zamek', 'Kultura żydowska']),
                'highlights' => json_encode(['Stare Miasto', 'Majdanek', 'Brama Krakowska']),
                'category' => 'kulturalne',
                'region' => 'Lubelskie',
                'active' => true,
            ],
            [
                'name' => 'Toruń',
                'description' => 'Miasto piernika i Kopernika',
                'long_description' => 'Toruń to średniowieczne miasto Kopernika, słynące z pierników i gotyckiej architektury.',
                'image' => '/images/destinations/torun-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Pierniki', 'Muzeum Kopernika', 'Stare Miasto']),
                'highlights' => json_encode(['Ratusz', 'Dom Kopernika', 'Planetarium']),
                'category' => 'kulturalne',
                'region' => 'Kujawsko-pomorskie',
                'active' => true,
            ],

            // Nadmorskie
            [
                'name' => 'Sopot',
                'description' => 'Elegancki kurort nad Bałtykiem',
                'long_description' => 'Sopot to najbardziej elegancki kurort nadmorski w Polsce z najdłuższym drewnianym molo.',
                'image' => '/images/destinations/sopot-main.jpg',
                'price' => 229.00,
                'original_price' => 269.00,
                'type' => 'Luksusowy',
                'duration' => '3 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Molo', 'Plaża', 'Monte Cassino']),
                'highlights' => json_encode(['Molo', 'Krzywy Domek', 'Grand Hotel']),
                'category' => 'nadmorskie',
                'region' => 'Pomorskie',
                'active' => true,
            ],
            [
                'name' => 'Kołobrzeg',
                'description' => 'Uzdrowisko nad Bałtykiem',
                'long_description' => 'Kołobrzeg to popularne uzdrowisko nadmorskie z szeroką plażą i bogatą ofertą SPA.',
                'image' => '/images/destinations/kolobrzeg-main.jpg',
                'price' => 209.00,
                'original_price' => 249.00,
                'type' => 'SPA',
                'duration' => '4 dni',
                'rating' => 4.7,
                'activities' => json_encode(['SPA', 'Plaża', 'Latarnia morska']),
                'highlights' => json_encode(['Plaża', 'Port', 'Latarnia']),
                'category' => 'nadmorskie',
                'region' => 'Zachodniopomorskie',
                'active' => true,
            ],
            [
                'name' => 'Świnoujście',
                'description' => 'Miasto na wyspach z najszerszą plażą',
                'long_description' => 'Świnoujście to unikalne miasto położone na trzech wyspach z najszerszą plażą w Polsce.',
                'image' => '/images/destinations/swinoujscie-main.jpg',
                'price' => 199.00,
                'original_price' => 239.00,
                'type' => 'Plażowy',
                'duration' => '3 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Plaża', 'Fort', 'Promenada']),
                'highlights' => json_encode(['Plaża', 'Latarnia', 'Fort Zachodni']),
                'category' => 'nadmorskie',
                'region' => 'Zachodniopomorskie',
                'active' => true,
            ],
            [
                'name' => 'Ustka',
                'description' => 'Malowniczy port rybacki nad Bałtykiem',
                'long_description' => 'Ustka to urokliwy port rybacki z piękną plażą i charakterystyczną latarnią morską.',
                'image' => '/images/destinations/ustka-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'Rodzinny',
                'duration' => '3 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Port rybacki', 'Plaża', 'Latarnia']),
                'highlights' => json_encode(['Port', 'Plaża', 'Latarnia morska']),
                'category' => 'nadmorskie',
                'region' => 'Pomorskie',
                'active' => true,
            ],
            [
                'name' => 'Międzyzdroje',
                'description' => 'Perła polskiego wybrzeża',
                'long_description' => 'Międzyzdroje to elegancki kurort nadmorski zwany Perłą Bałtyku z piękną plażą.',
                'image' => '/images/destinations/miedzyzdroje-main.jpg',
                'price' => 219.00,
                'original_price' => 259.00,
                'type' => 'Elegancki',
                'duration' => '3 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Molo', 'Wax museum', 'Klify']),
                'highlights' => json_encode(['Molo', 'Aleja Gwiazd', 'Park Narodowy']),
                'category' => 'nadmorskie',
                'region' => 'Zachodniopomorskie',
                'active' => true,
            ],

            // Mazury i jeziora
            [
                'name' => 'Giżycko',
                'description' => 'Stolica Mazur - kraina tysiąca jezior',
                'long_description' => 'Giżycko to stolica Mazur, centrum żeglarstwa i turystyki wodnej w krainie tysiąca jezior.',
                'image' => '/images/destinations/gizycko-main.jpg',
                'price' => 189.00,
                'original_price' => 229.00,
                'type' => 'Wodny',
                'duration' => '4 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Żeglarstwo', 'Kajaki', 'Ryby']),
                'highlights' => json_encode(['Kanał Łuczański', 'Fortress Boyen', 'Jezioro Niegocin']),
                'category' => 'przyrodnicze',
                'region' => 'Warmińsko-mazurskie',
                'active' => true,
            ],
            [
                'name' => 'Mikołajki',
                'description' => 'Mazurska Wenecja pełna uroku',
                'long_description' => 'Mikołajki to urocze miasteczko nazywane Mazurską Wenecją, centrum turystyki wodnej.',
                'image' => '/images/destinations/mikolajki-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'Romantyczny',
                'duration' => '3 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Żeglarstwo', 'Spacery', 'Restauracje']),
                'highlights' => json_encode(['Port', 'Jezioro Mikołajskie', 'Centrum']),
                'category' => 'przyrodnicze',
                'region' => 'Warmińsko-mazurskie',
                'active' => true,
            ],
            [
                'name' => 'Mrągowo',
                'description' => 'Centrum kultury i sportu na Mazurach',
                'long_description' => 'Mrągowo to dynamiczne miasto na Mazurach słynące z festiwali i imprez kulturalnych.',
                'image' => '/images/destinations/mragowo-main.jpg',
                'price' => 169.00,
                'original_price' => 209.00,
                'type' => 'Kulturalny',
                'duration' => '3 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Festiwale', 'Koncerty', 'Jeziora']),
                'highlights' => json_encode(['Amfiteatr', 'Jezioro Czos', 'Rynek']),
                'category' => 'kulturalne',
                'region' => 'Warmińsko-mazurskie',
                'active' => true,
            ],

            // Podlasie i wschód
            [
                'name' => 'Białowieża',
                'description' => 'Ostatnia pierwotna puszcza Europy',
                'long_description' => 'Białowieża to unikalne miejsce z ostatnią pierwotną puszczą Europy i żubrami.',
                'image' => '/images/destinations/bialowieza-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Ekoturystyka',
                'duration' => '2 dni',
                'rating' => 4.9,
                'activities' => json_encode(['Safari żubrów', 'Puszcza', 'Rezerwat']),
                'highlights' => json_encode(['Puszcza', 'Żubry', 'Ścieżki przyrodnicze']),
                'category' => 'przyrodnicze',
                'region' => 'Podlaskie',
                'active' => true,
            ],
            [
                'name' => 'Augustów',
                'description' => 'Stolica polskich kajaków',
                'long_description' => 'Augustów to malownicze miasto nad Nettą, stolica polskiego kajakarstwa.',
                'image' => '/images/destinations/augustow-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Aktywny',
                'duration' => '3 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Kajaki', 'Kanał Augustowski', 'Puszcza']),
                'highlights' => json_encode(['Kanał Augustowski', 'Śluzy', 'Jeziora']),
                'category' => 'przyrodnicze',
                'region' => 'Podlaskie',
                'active' => true,
            ],

            // Śląsk i okolice
            [
                'name' => 'Katowice',
                'description' => 'Nowoczesne centrum Śląska',
                'long_description' => 'Katowice to nowoczesne centrum Śląska z bogatą ofertą kulturalną i rozrywkową.',
                'image' => '/images/destinations/katowice-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Miejski',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Spodek', 'NOSPR', 'Muzea']),
                'highlights' => json_encode(['Spodek', 'Strefa Kultury', 'Nikiszowiec']),
                'category' => 'kulturalne',
                'region' => 'Śląskie',
                'active' => true,
            ],
            [
                'name' => 'Częstochowa',
                'description' => 'Duchowa stolica Polski',
                'long_description' => 'Częstochowa to duchowa stolica Polski z słynnym sanktuarium na Jasnej Górze.',
                'image' => '/images/destinations/czestochowa-main.jpg',
                'price' => 139.00,
                'original_price' => 179.00,
                'type' => 'Pielgrzymkowy',
                'duration' => '2 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Jasna Góra', 'Pielgrzymka', 'Muzea']),
                'highlights' => json_encode(['Jasna Góra', 'Czarna Madonna', 'Klasztor']),
                'category' => 'kulturalne',
                'region' => 'Śląskie',
                'active' => true,
            ],

            // Kaszuby
            [
                'name' => 'Kartuzy',
                'description' => 'Serce Kaszub z jeziorami',
                'long_description' => 'Kartuzy to serce Kaszub, region o unikalnej kulturze i tradycjach nad jeziorami.',
                'image' => '/images/destinations/kartuzy-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Kultura kaszubska', 'Jeziora', 'Rękodzieło']),
                'highlights' => json_encode(['Muzeum Kaszubskie', 'Jeziora', 'Tradycje']),
                'category' => 'kulturalne',
                'region' => 'Pomorskie',
                'active' => true,
            ],

            // Dolny Śląsk
            [
                'name' => 'Kłodzko',
                'description' => 'Perła Ziemi Kłodzkiej',
                'long_description' => 'Kłodzko to malownicze miasto w Kotlinie Kłodzkiej z bogatą historią i zabytkami.',
                'image' => '/images/destinations/klodzko-main.jpg',
                'price' => 139.00,
                'original_price' => 179.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Podziemia', 'Twierdza', 'Stare Miasto']),
                'highlights' => json_encode(['Twierdza', 'Podziemia', 'Most gotycki']),
                'category' => 'kulturalne',
                'region' => 'Dolnośląskie',
                'active' => true,
            ],
            [
                'name' => 'Świdnica',
                'description' => 'Miasto z drewnianym kościołem UNESCO',
                'long_description' => 'Świdnica to miasto z unikalnym drewnianym kościołem wpisanym na listę UNESCO.',
                'image' => '/images/destinations/swidnica-main.jpg',
                'price' => 129.00,
                'original_price' => 169.00,
                'type' => 'Kulturalny',
                'duration' => '1 dzień',
                'rating' => 4.4,
                'activities' => json_encode(['Kościół drewniany', 'Rynek', 'Muzea']),
                'highlights' => json_encode(['Kościół Pokoju', 'Rynek', 'Ratusz']),
                'category' => 'kulturalne',
                'region' => 'Dolnośląskie',
                'active' => true,
            ],

            // Lubuskie
            [
                'name' => 'Zielona Góra',
                'description' => 'Stolica polskiego wina',
                'long_description' => 'Zielona Góra to stolica polskiego wina z tradycjami winiarskimi i festiwalami.',
                'image' => '/images/destinations/zielona-gora-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Winny',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Winnice', 'Degustacje', 'Festiwal']),
                'highlights' => json_encode(['Winnice', 'Stare Miasto', 'Festiwal Winobrania']),
                'category' => 'kulturalne',
                'region' => 'Lubuskie',
                'active' => true,
            ],

            // Opolskie
            [
                'name' => 'Opole',
                'description' => 'Stolica polskiej piosenki',
                'long_description' => 'Opole to miasto słynące z festiwalu polskiej piosenki i pięknej starówki nad Odrą.',
                'image' => '/images/destinations/opole-main.jpg',
                'price' => 139.00,
                'original_price' => 179.00,
                'type' => 'Muzyczny',
                'duration' => '2 dni',
                'rating' => 4.4,
                'activities' => json_encode(['Festiwal', 'Odra', 'Amfiteatr']),
                'highlights' => json_encode(['Amfiteatr', 'Stare Miasto', 'Odra']),
                'category' => 'kulturalne',
                'region' => 'Opolskie',
                'active' => true,
            ],

            // Małopolska
            [
                'name' => 'Nowy Sącz',
                'description' => 'Brama do Beskidu Sądeckiego',
                'long_description' => 'Nowy Sącz to brama do Beskidu Sądeckiego z piękną starówką i zabytkami.',
                'image' => '/images/destinations/nowy-sacz-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Stare Miasto', 'Skanzen', 'Góry']),
                'highlights' => json_encode(['Rynek', 'Skanzen', 'Beskid Sądecki']),
                'category' => 'kulturalne',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Tarnów',
                'description' => 'Perła polskiego renesansu',
                'long_description' => 'Tarnów to miasto o bogatej historii z najlepiej zachowaną renesansową starówką.',
                'image' => '/images/destinations/tarnow-main.jpg',
                'price' => 129.00,
                'original_price' => 169.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.4,
                'activities' => json_encode(['Renesans', 'Kamienice', 'Muzea']),
                'highlights' => json_encode(['Rynek', 'Ratusz', 'Katedra']),
                'category' => 'kulturalne',
                'region' => 'Małopolska',
                'active' => true,
            ],

            // Podkarpacie
            [
                'name' => 'Rzeszów',
                'description' => 'Stolica innowacji na Podkarpaciu',
                'long_description' => 'Rzeszów to dynamicznie rozwijające się miasto, stolica Podkarpacia z bogatą historią.',
                'image' => '/images/destinations/rzeszow-main.jpg',
                'price' => 139.00,
                'original_price' => 179.00,
                'type' => 'Miejski',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Podziemia', 'Rynek', 'Technologia']),
                'highlights' => json_encode(['Podziemia', 'Rynek', 'Zamek']),
                'category' => 'kulturalne',
                'region' => 'Podkarpackie',
                'active' => true,
            ],
            [
                'name' => 'Przemyśl',
                'description' => 'Miasto na pograniczu kultur',
                'long_description' => 'Przemyśl to miasto na pograniczu kultur z bogatą historią i zabytkami.',
                'image' => '/images/destinations/przemysl-main.jpg',
                'price' => 129.00,
                'original_price' => 169.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.4,
                'activities' => json_encode(['Zamek', 'Cerkwie', 'Twierdza']),
                'highlights' => json_encode(['Zamek', 'Stare Miasto', 'San']),
                'category' => 'kulturalne',
                'region' => 'Podkarpackie',
                'active' => true,
            ],
            [
                'name' => 'Sanok',
                'description' => 'Stolica Bieszczadów',
                'long_description' => 'Sanok to malownicze miasto u podnóża Bieszczadów z bogatą kulturą ludową.',
                'image' => '/images/destinations/sanok-main.jpg',
                'price' => 139.00,
                'original_price' => 179.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Skansen', 'Zamek', 'Bieszczady']),
                'highlights' => json_encode(['Skansen', 'Zamek', 'Muzeum Narodowe']),
                'category' => 'kulturalne',
                'region' => 'Podkarpackie',
                'active' => true,
            ],

            // Świętokrzyskie
            [
                'name' => 'Kielce',
                'description' => 'Stolica Gór Świętokrzyskich',
                'long_description' => 'Kielce to stolica województwa świętokrzyskiego u podnóża najstarszych gór w Polsce.',
                'image' => '/images/destinations/kielce-main.jpg',
                'price' => 129.00,
                'original_price' => 169.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.4,
                'activities' => json_encode(['Pałac Biskupów', 'Góry', 'Muzea']),
                'highlights' => json_encode(['Pałac Biskupów', 'Kadzielnia', 'Góry Świętokrzyskie']),
                'category' => 'kulturalne',
                'region' => 'Świętokrzyskie',
                'active' => true,
            ],

            // Łódzkie
            [
                'name' => 'Łódź',
                'description' => 'Miasto trzech kultur',
                'long_description' => 'Łódź to miasto trzech kultur z bogatą historią przemysłową i artystyczną.',
                'image' => '/images/destinations/lodz-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Kulturalny',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Piotrkowska', 'Manufaktura', 'Sztuka']),
                'highlights' => json_encode(['Piotrkowska', 'Manufaktura', 'EC1']),
                'category' => 'kulturalne',
                'region' => 'Łódzkie',
                'active' => true,
            ],

            // Specjalne miejsca
            [
                'name' => 'Malbork',
                'description' => 'Największy zamek na świecie',
                'long_description' => 'Malbork to miasto z największym zamkiem ceglowym na świecie, siedzibą krzyżaków.',
                'image' => '/images/destinations/malbork-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Kulturalny',
                'duration' => '1 dzień',
                'rating' => 4.8,
                'activities' => json_encode(['Zamek', 'Historia', 'Muzeum']),
                'highlights' => json_encode(['Zamek krzyżacki', 'Nogat', 'Muzeum']),
                'category' => 'kulturalne',
                'region' => 'Pomorskie',
                'active' => true,
            ],
            [
                'name' => 'Oświęcim',
                'description' => 'Miejsce pamięci i edukacji',
                'long_description' => 'Oświęcim to ważne miejsce pamięci z Muzeum Auschwitz-Birkenau.',
                'image' => '/images/destinations/oswiecim-main.jpg',
                'price' => 99.00,
                'original_price' => 139.00,
                'type' => 'Edukacyjny',
                'duration' => '1 dzień',
                'rating' => 4.9,
                'activities' => json_encode(['Muzeum', 'Pamięć', 'Edukacja']),
                'highlights' => json_encode(['Auschwitz-Birkenau', 'Muzeum', 'Centrum Edukacji']),
                'category' => 'kulturalne',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Wieliczka',
                'description' => 'Podziemne miasto w soli',
                'long_description' => 'Wieliczka to miasto słynące z kopalni soli wpisanej na listę UNESCO.',
                'image' => '/images/destinations/wieliczka-main.jpg',
                'price' => 119.00,
                'original_price' => 159.00,
                'type' => 'Podziemny',
                'duration' => '1 dzień',
                'rating' => 4.8,
                'activities' => json_encode(['Kopalnia soli', 'Podziemia', 'Kaplica']),
                'highlights' => json_encode(['Kopalnia soli', 'Kaplica św. Kingi', 'Jezioro']),
                'category' => 'kulturalne',
                'region' => 'Małopolska',
                'active' => true,
            ],

            // Parki narodowe
            [
                'name' => 'Ojców',
                'description' => 'Najmniejszy park narodowy',
                'long_description' => 'Ojców to najmniejszy park narodowy w Polsce z malowniczymi skałami i zamkami.',
                'image' => '/images/destinations/ojcow-main.jpg',
                'price' => 109.00,
                'original_price' => 149.00,
                'type' => 'Przyrodniczy',
                'duration' => '1 dzień',
                'rating' => 4.7,
                'activities' => json_encode(['Skały', 'Zamki', 'Przyroda']),
                'highlights' => json_encode(['Maczuga Herkulesa', 'Zamek w Ojcowie', 'Jaskinie']),
                'category' => 'przyrodnicze',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Słowiński Park Narodowy',
                'description' => 'Ruchome wydmy nad Bałtykiem',
                'long_description' => 'Słowiński Park Narodowy to unikalne miejsce z ruchomymi wydmami nad Bałtykiem.',
                'image' => '/images/destinations/slowinski-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Przyrodniczy',
                'duration' => '2 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Wydmy', 'Plaża', 'Latarnia']),
                'highlights' => json_encode(['Ruchome wydmy', 'Łacka Łąka', 'Latarnia Słowińska']),
                'category' => 'przyrodnicze',
                'region' => 'Pomorskie',
                'active' => true,
            ],

            // Termy i SPA
            [
                'name' => 'Bukowina Termy',
                'description' => 'Relaks w termalnych wodach',
                'long_description' => 'Bukowina Termy to nowoczesny kompleks termalny u podnóża Tatr.',
                'image' => '/images/destinations/bukowina-termy-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'SPA',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Termy', 'SPA', 'Relaks']),
                'highlights' => json_encode(['Baseny termalne', 'SPA', 'Tatry']),
                'category' => 'relaksacyjne',
                'region' => 'Małopolska',
                'active' => true,
            ],
            [
                'name' => 'Cieplice',
                'description' => 'Najstarsze uzdrowisko w Polsce',
                'long_description' => 'Cieplice to najstarsze uzdrowisko w Polsce z naturalnymi źródłami termalnymi.',
                'image' => '/images/destinations/cieplice-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Uzdrowiskowy',
                'duration' => '3 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Termy', 'Sanatorium', 'Park']),
                'highlights' => json_encode(['Źródła termalne', 'Park Zdrojowy', 'Sanatoria']),
                'category' => 'uzdrowiskowe',
                'region' => 'Dolnośląskie',
                'active' => true,
            ],

            // Roztocze
            [
                'name' => 'Zwierzyniec',
                'description' => 'Serce Roztocza',
                'long_description' => 'Zwierzyniec to urokliwe miasteczko w sercu Roztocza z unikalną przyrodą.',
                'image' => '/images/destinations/zwierzyniec-main.jpg',
                'price' => 129.00,
                'original_price' => 169.00,
                'type' => 'Przyrodniczy',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Roztoczański PN', 'Żubry', 'Jeziora']),
                'highlights' => json_encode(['Roztoczański PN', 'Rezerwat żubrów', 'Echo']),
                'category' => 'przyrodnicze',
                'region' => 'Lubelskie',
                'active' => true,
            ],

            // Jurajskie
            [
                'name' => 'Ogrodzieniec',
                'description' => 'Orle Gniazda na Jurze',
                'long_description' => 'Ogrodzieniec to miejsce z malowniczymi ruinami zamku na Jurze Krakowsko-Częstochowskiej.',
                'image' => '/images/destinations/ogrodzieniec-main.jpg',
                'price' => 99.00,
                'original_price' => 139.00,
                'type' => 'Kulturalny',
                'duration' => '1 dzień',
                'rating' => 4.7,
                'activities' => json_encode(['Zamek', 'Jura', 'Skały']),
                'highlights' => json_encode(['Ruiny zamku', 'Skały', 'Jura']),
                'category' => 'kulturalne',
                'region' => 'Śląskie',
                'active' => true,
            ],

            // Warmia
            [
                'name' => 'Olsztyn',
                'description' => 'Stolica Warmii i Mazur',
                'long_description' => 'Olsztyn to stolica Warmii i Mazur z pięknym zamkiem i jeziorami.',
                'image' => '/images/destinations/olsztyn-main.jpg',
                'price' => 149.00,
                'original_price' => 189.00,
                'type' => 'Miejski',
                'duration' => '2 dni',
                'rating' => 4.6,
                'activities' => json_encode(['Zamek', 'Jeziora', 'Planety']),
                'highlights' => json_encode(['Zamek', 'Stare Miasto', 'Ukiel']),
                'category' => 'kulturalne',
                'region' => 'Warmińsko-mazurskie',
                'active' => true,
            ],

            // Bory Tucholskie
            [
                'name' => 'Tuchola',
                'description' => 'Serce Borów Tucholskich',
                'long_description' => 'Tuchola to miasto w sercu Borów Tucholskich z czystymi jeziorami i lasami.',
                'image' => '/images/destinations/tuchola-main.jpg',
                'price' => 119.00,
                'original_price' => 159.00,
                'type' => 'Przyrodniczy',
                'duration' => '2 dni',
                'rating' => 4.5,
                'activities' => json_encode(['Lasy', 'Jeziora', 'Grzyby']),
                'highlights' => json_encode(['Bory Tucholskie', 'Jeziora', 'Park Krajobrazowy']),
                'category' => 'przyrodnicze',
                'region' => 'Kujawsko-pomorskie',
                'active' => true,
            ],

            // Bieszczady
            [
                'name' => 'Ustrzyki Dolne',
                'description' => 'Brama do Bieszczadów',
                'long_description' => 'Ustrzyki Dolne to brama do Bieszczadów, najdzikszych gór Polski.',
                'image' => '/images/destinations/ustrzyki-main.jpg',
                'price' => 159.00,
                'original_price' => 199.00,
                'type' => 'Górski',
                'duration' => '3 dni',
                'rating' => 4.8,
                'activities' => json_encode(['Hiking', 'Wilderness', 'Żubry']),
                'highlights' => json_encode(['Bieszczadzki PN', 'Połoniny', 'Tarnica']),
                'category' => 'górskie',
                'region' => 'Podkarpackie',
                'active' => true,
            ],

            // Pieniny
            [
                'name' => 'Krościenko',
                'description' => 'Serce Pienin nad Dunajcem',
                'long_description' => 'Krościenko to malownicze miasteczko w sercu Pienin nad Dunajcem.',
                'image' => '/images/destinations/kroscenko-main.jpg',
                'price' => 139.00,
                'original_price' => 179.00,
                'type' => 'Górski',
                'duration' => '2 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Spływ Dunajcem', 'Trzy Korony', 'Pieniny']),
                'highlights' => json_encode(['Spływ Dunajcem', 'Trzy Korony', 'Pieniński PN']),
                'category' => 'górskie',
                'region' => 'Małopolska',
                'active' => true,
            ],

            // Beskidy
            [
                'name' => 'Krynica-Zdrój',
                'description' => 'Perła polskich uzdrowisk',
                'long_description' => 'Krynica-Zdrój to eleganckie uzdrowisko w Beskidzie Sądeckim.',
                'image' => '/images/destinations/krynica-main.jpg',
                'price' => 179.00,
                'original_price' => 219.00,
                'type' => 'Uzdrowiskowy',
                'duration' => '3 dni',
                'rating' => 4.7,
                'activities' => json_encode(['Wody mineralne', 'Parkowa Góra', 'SPA']),
                'highlights' => json_encode(['Stary Dom Zdrojowy', 'Parkowa Góra', 'Pijalnia']),
                'category' => 'uzdrowiskowe',
                'region' => 'Małopolska',
                'active' => true,
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::create($destination);
        }
    }
}
